In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Visadataset.csv")

In [3]:
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [4]:
df.shape

(25480, 12)

In [5]:
data = df.to_dict(orient = "records")

In [6]:
#data

In [7]:
len(data)

25480

In [8]:
DB_NAME = "US_VISA"
COLLECTION_NAME = "visa_data"
CONNECTION_URL = "mongodb+srv://masud72:masud72@cluster0.atoi34e.mongodb.net/?appName=Cluster0"

In [9]:
import pymongo

In [10]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

rec = collection.insert_many(data)

In [11]:
records = collection.find()
records

In [12]:
for i, j in enumerate(records):
    print(f"{i}: {j}")

0: {'_id': ObjectId('6a0c92e7a6fc024582dfd226'), 'case_id': 'EZYV01', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 14513, 'yr_of_estab': 2007, 'region_of_employment': 'West', 'prevailing_wage': 592.2029, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Denied'}
1: {'_id': ObjectId('6a0c92e7a6fc024582dfd227'), 'case_id': 'EZYV02', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2412, 'yr_of_estab': 2002, 'region_of_employment': 'Northeast', 'prevailing_wage': 83425.65, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
2: {'_id': ObjectId('6a0c92e7a6fc024582dfd228'), 'case_id': 'EZYV03', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 44444, 'yr_of_estab': 2008, 'region_of_employment': 'West', 'prevailing_wage': 122996.86, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
3: {'_id': ObjectId('6a0c92e7a6fc024582dfd229'), 'case_id': 'EZYV04', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 98, 'yr_of_estab': 1897, 'region_of_employment': 'West', 'prevailing_wage': 83434.03, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
4: {'_id': ObjectId('6a0c92e7a6fc024582dfd22a'), 'case_id': 'EZYV05', 'continent': 'Africa', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1082, 'yr_of_estab': 2005, 'region_of_employment': 'South', 'prevailing_wage': 149907.39, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
5: {'_id': ObjectId('6a0c92e7a6fc024582dfd22b'), 'case_id': 'EZYV06', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2339, 'yr_of_estab': 2012, 'region_of_employment': 'South', 'prevailing_wage': 78252.14, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
6: {'_id': ObjectId('6a0c92e7a6fc024582dfd22c'), 'case_id': 'EZYV07', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 4985, 'yr_of_estab': 1994, 'region_of_employment': 'South', 'prevailing_wage': 53635.39, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
7: {'_id': ObjectId('6a0c92e7a6fc024582dfd22d'), 'case_id': 'EZYV08', 'continent': 'North America', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3035, 'yr_of_estab': 1924, 'region_of_employment': 'West', 'prevailing_wage': 418.2298, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Denied'}
8: {'_id': ObjectId('6a0c92e7a6fc024582dfd22e'), 'case_id': 'EZYV09', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 4810, 'yr_of_estab': 2012, 'region_of_employment': 'Midwest', 'prevailing_wage': 74362.19, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
9: {'_id': ObjectId('6a0c92e7a6fc024582dfd22f'), 'case_id': 'EZYV10', 'continent': 'Europe', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2251, 'yr_of_estab': 1995, 'region_of_employment': 'South', 'prevailing_wage': 67514.76, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
10: {'_id': ObjectId('6a0c92e7a6fc024582dfd230'), 'case_id': 'EZYV11', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2465, 'yr_of_estab': 2004, 'region_of_employment': 'Midwest', 'prevailing_wage': 83588.56, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
11: {'_id': ObjectId('6a0c92e7a6fc024582dfd231'), 'case_id': 'EZYV12', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4069, 'yr_of_estab': 2005, 'region_of_employment': 'Northeast', 'prevailing_wage': 70813.09, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
12: {'_id': ObjectId('6a0c92e7a6fc024582dfd232'), 'case_id': 'EZYV13', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 123876, 'yr_of_estab': 1963, 'region_of_employment': 'Northeast', 'prevailing_wage': 28663.05, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
13: {'_id': ObjectId('6a0c92e7a6fc024582dfd233'), 'case_id': 'EZYV14', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1652, 'yr_of_estab': 2007, 'region_of_employment': 'Midwest', 'prevailing_wage': 107196.03, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
14: {'_id': ObjectId('6a0c92e7a6fc024582dfd234'), 'case_id': 'EZYV15', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 15756, 'yr_of_estab': 2006, 'region_of_employment': 'South', 'prevailing_wage': 220081.73, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
15: {'_id': ObjectId('6a0c92e7a6fc024582dfd235'), 'case_id': 'EZYV16', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4897, 'yr_of_estab': 1987, 'region_of_employment': 'West', 'prevailing_wage': 74108.02, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
16: {'_id': ObjectId('6a0c92e7a6fc024582dfd236'), 'case_id': 'EZYV17', 'continent': 'Europe', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 76638, 'yr_of_estab': 1991, 'region_of_employment': 'Midwest', 'prevailing_wage': 3706.79, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
17: {'_id': ObjectId('6a0c92e7a6fc024582dfd237'), 'case_id': 'EZYV18', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2747, 'yr_of_estab': 2001, 'region_of_employment': 'West', 'prevailing_wage': 16132.61, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
18: {'_id': ObjectId('6a0c92e7a6fc024582dfd238'), 'case_id': 'EZYV19', 'continent': 'Africa', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4743, 'yr_of_estab': 2004, 'region_of_employment': 'Midwest', 'prevailing_wage': 150441.13, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
19: {'_id': ObjectId('6a0c92e7a6fc024582dfd239'), 'case_id': 'EZYV20', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 843, 'yr_of_estab': 1972, 'region_of_employment': 'Midwest', 'prevailing_wage': 79948.12, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20: {'_id': ObjectId('6a0c92e7a6fc024582dfd23a'), 'case_id': 'EZYV21', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 880, 'yr_of_estab': 2008, 'region_of_employment': 'West', 'prevailing_wage': 71128.98, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
21: {'_id': ObjectId('6a0c92e7a6fc024582dfd23b'), 'case_id': 'EZYV22', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1706, 'yr_of_estab': 2013, 'region_of_employment': 'Midwest', 'prevailing_wage': 137694.98, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
22: {'_id': ObjectId('6a0c92e7a6fc024582dfd23c'), 'case_id': 'EZYV23', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2878, 'yr_of_estab': 1968, 'region_of_employment': 'West', 'prevailing_wage': 45642.39, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
23: {'_id': ObjectId('6a0c92e7a6fc024582dfd23d'), 'case_id': 'EZYV24', 'continent': 'North America', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1517, 'yr_of_estab': 1884, 'region_of_employment': 'Midwest', 'prevailing_wage': 90108.38, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
24: {'_id': ObjectId('6a0c92e7a6fc024582dfd23e'), 'case_id': 'EZYV25', 'continent': 'Europe', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 241, 'yr_of_estab': 1981, 'region_of_employment': 'Midwest', 'prevailing_wage': 71286.04, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
25: {'_id': ObjectId('6a0c92e7a6fc024582dfd23f'), 'case_id': 'EZYV26', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1100, 'yr_of_estab': 1997, 'region_of_employment': 'Midwest', 'prevailing_wage': 99489.65, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
26: {'_id': ObjectId('6a0c92e7a6fc024582dfd240'), 'case_id': 'EZYV27', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 756, 'yr_of_estab': 1995, 'region_of_employment': 'South', 'prevailing_wage': 86332.95, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
27: {'_id': ObjectId('6a0c92e7a6fc024582dfd241'), 'case_id': 'EZYV28', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 2889, 'yr_of_estab': 2005, 'region_of_employment': 'South', 'prevailing_wage': 103029.33, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
28: {'_id': ObjectId('6a0c92e7a6fc024582dfd242'), 'case_id': 'EZYV29', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 18, 'yr_of_estab': 2004, 'region_of_employment': 'Northeast', 'prevailing_wage': 40925.86, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
29: {'_id': ObjectId('6a0c92e7a6fc024582dfd243'), 'case_id': 'EZYV30', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 758, 'yr_of_estab': 2009, 'region_of_employment': 'Northeast', 'prevailing_wage': 189190.48, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
30: {'_id': ObjectId('6a0c92e7a6fc024582dfd244'), 'case_id': 'EZYV31', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1408, 'yr_of_estab': 1998, 'region_of_employment': 'Midwest', 'prevailing_wage': 79594.12, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
31: {'_id': ObjectId('6a0c92e7a6fc024582dfd245'), 'case_id': 'EZYV32', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 995, 'yr_of_estab': 1880, 'region_of_employment': 'South', 'prevailing_wage': 135866.13, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
32: {'_id': ObjectId('6a0c92e7a6fc024582dfd246'), 'case_id': 'EZYV33', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2415, 'yr_of_estab': 1963, 'region_of_employment': 'Midwest', 'prevailing_wage': 72077.57, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
33: {'_id': ObjectId('6a0c92e7a6fc024582dfd247'), 'case_id': 'EZYV34', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2395, 'yr_of_estab': 2000, 'region_of_employment': 'South', 'prevailing_wage': 81921.18, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
34: {'_id': ObjectId('6a0c92e7a6fc024582dfd248'), 'case_id': 'EZYV35', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1809, 'yr_of_estab': 2010, 'region_of_employment': 'South', 'prevailing_wage': 225569.73, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
35: {'_id': ObjectId('6a0c92e7a6fc024582dfd249'), 'case_id': 'EZYV36', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 5512, 'yr_of_estab': 2001, 'region_of_employment': 'Northeast', 'prevailing_wage': 92421.92, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
36: {'_id': ObjectId('6a0c92e7a6fc024582dfd24a'), 'case_id': 'EZYV37', 'continent': 'Europe', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2520, 'yr_of_estab': 1981, 'region_of_employment': 'West', 'prevailing_wage': 2490.12, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
37: {'_id': ObjectId('6a0c92e7a6fc024582dfd24b'), 'case_id': 'EZYV38', 'continent': 'Europe', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 44, 'yr_of_estab': 1965, 'region_of_employment': 'South', 'prevailing_wage': 110817.26, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
38: {'_id': ObjectId('6a0c92e7a6fc024582dfd24c'), 'case_id': 'EZYV39', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 2206, 'yr_of_estab': 1909, 'region_of_employment': 'Northeast', 'prevailing_wage': 50960.01, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
39: {'_id': ObjectId('6a0c92e7a6fc024582dfd24d'), 'case_id': 'EZYV40', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 3729, 'yr_of_estab': 2007, 'region_of_employment': 'Midwest', 'prevailing_wage': 125336.9, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
40: {'_id': ObjectId('6a0c92e7a6fc024582dfd24e'), 'case_id': 'EZYV41', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3723, 'yr_of_estab': 2011, 'region_of_employment': 'West', 'prevailing_wage': 39633.32, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
41: {'_id': ObjectId('6a0c92e7a6fc024582dfd24f'), 'case_id': 'EZYV42', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1209, 'yr_of_estab': 1989, 'region_of_employment': 'Northeast', 'prevailing_wage': 156326.33, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
42: {'_id': ObjectId('6a0c92e7a6fc024582dfd250'), 'case_id': 'EZYV43', 'continent': 'Europe', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 19770, 'yr_of_estab': 2005, 'region_of_employment': 'West', 'prevailing_wage': 43630.58, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
43: {'_id': ObjectId('6a0c92e7a6fc024582dfd251'), 'case_id': 'EZYV44', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2582, 'yr_of_estab': 1989, 'region_of_employment': 'South', 'prevailing_wage': 54614.42, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
44: {'_id': ObjectId('6a0c92e7a6fc024582dfd252'), 'case_id': 'EZYV45', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 5407, 'yr_of_estab': 1998, 'region_of_employment': 'West', 'prevailing_wage': 28989.87, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
45: {'_id': ObjectId('6a0c92e7a6fc024582dfd253'), 'case_id': 'EZYV46', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 2092, 'yr_of_estab': 1998, 'region_of_employment': 'South', 'prevailing_wage': 22924.91, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
46: {'_id': ObjectId('6a0c92e7a6fc024582dfd254'), 'case_id': 'EZYV47', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2623, 'yr_of_estab': 2008, 'region_of_employment': 'South', 'prevailing_wage': 61567.75, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
47: {'_id': ObjectId('6a0c92e7a6fc024582dfd255'), 'case_id': 'EZYV48', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 226, 'yr_of_estab': 1991, 'region_of_employment': 'Midwest', 'prevailing_wage': 156251.17, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
48: {'_id': ObjectId('6a0c92e7a6fc024582dfd256'), 'case_id': 'EZYV49', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2405, 'yr_of_estab': 1933, 'region_of_employment': 'South', 'prevailing_wage': 86022.02, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49: {'_id': ObjectId('6a0c92e7a6fc024582dfd257'), 'case_id': 'EZYV50', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 2171, 'yr_of_estab': 1960, 'region_of_employment': 'Northeast', 'prevailing_wage': 49565.37, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
50: {'_id': ObjectId('6a0c92e7a6fc024582dfd258'), 'case_id': 'EZYV51', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 746, 'yr_of_estab': 1991, 'region_of_employment': 'Midwest', 'prevailing_wage': 66191.41, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
51: {'_id': ObjectId('6a0c92e7a6fc024582dfd259'), 'case_id': 'EZYV52', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3129, 'yr_of_estab': 2003, 'region_of_employment': 'Midwest', 'prevailing_wage': 95623.2, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
52: {'_id': ObjectId('6a0c92e7a6fc024582dfd25a'), 'case_id': 'EZYV53', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1647, 'yr_of_estab': 1998, 'region_of_employment': 'Midwest', 'prevailing_wage': 115014.05, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

49932: {'_id': ObjectId('6a0c94afb1dae384ec1909f5'), 'case_id': 'EZYV24453', 'continent': 'South America', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2148, 'yr_of_estab': 2009, 'region_of_employment': 'South', 'prevailing_wage': 116671.74, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49933: {'_id': ObjectId('6a0c94afb1dae384ec1909f6'), 'case_id': 'EZYV24454', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1166, 'yr_of_estab': 2004, 'region_of_employment': 'West', 'prevailing_wage': 105408.45, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49934: {'_id': ObjectId('6a0c94afb1dae384ec1909f7'), 'case_id': 'EZYV24455', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2804, 'yr_of_estab': 1963, 'region_of_employment': 'West', 'prevailing_wage': 54618.43, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Denied'}
49935: {'_id': ObjectId('6a0c94afb1dae384ec1909f8'), 'case_id': 'EZYV24456', 'continent': 'North America', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2957, 'yr_of_estab': 1855, 'region_of_employment': 'Northeast', 'prevailing_wage': 59584.77, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49936: {'_id': ObjectId('6a0c94afb1dae384ec1909f9'), 'case_id': 'EZYV24457', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1636, 'yr_of_estab': 2010, 'region_of_employment': 'South', 'prevailing_wage': 19550.32, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49937: {'_id': ObjectId('6a0c94afb1dae384ec1909fa'), 'case_id': 'EZYV24458', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 3529, 'yr_of_estab': 1925, 'region_of_employment': 'Midwest', 'prevailing_wage': 66659.34, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49938: {'_id': ObjectId('6a0c94afb1dae384ec1909fb'), 'case_id': 'EZYV24459', 'continent': 'North America', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 559, 'yr_of_estab': 2004, 'region_of_employment': 'Northeast', 'prevailing_wage': 84200.89, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Denied'}
49939: {'_id': ObjectId('6a0c94afb1dae384ec1909fc'), 'case_id': 'EZYV24460', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 838, 'yr_of_estab': 2009, 'region_of_employment': 'West', 'prevailing_wage': 132681.91, 'unit_of_wage': 'Week', 'full_time_position': 'Y', 'case_status': 'Certified'}
49940: {'_id': ObjectId('6a0c94afb1dae384ec1909fd'), 'case_id': 'EZYV24461', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2065, 'yr_of_estab': 1985, 'region_of_employment': 'South', 'prevailing_wage': 124434.41, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
49941: {'_id': ObjectId('6a0c94afb1dae384ec1909fe'), 'case_id': 'EZYV24462', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1619, 'yr_of_estab': 1945, 'region_of_employment': 'South', 'prevailing_wage': 56723.09, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
49942: {'_id': ObjectId('6a0c94afb1dae384ec1909ff'), 'case_id': 'EZYV24463', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 880, 'yr_of_estab': 1983, 'region_of_employment': 'Northeast', 'prevailing_wage': 86411.75, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
49943: {'_id': ObjectId('6a0c94afb1dae384ec190a00'), 'case_id': 'EZYV24464', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1405, 'yr_of_estab': 1982, 'region_of_employment': 'Midwest', 'prevailing_wage': 176181.85, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49944: {'_id': ObjectId('6a0c94afb1dae384ec190a01'), 'case_id': 'EZYV24465', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2277, 'yr_of_estab': 1995, 'region_of_employment': 'Midwest', 'prevailing_wage': 115635.85, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
49945: {'_id': ObjectId('6a0c94afb1dae384ec190a02'), 'case_id': 'EZYV24466', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3816, 'yr_of_estab': 2009, 'region_of_employment': 'Midwest', 'prevailing_wage': 60948.15, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49946: {'_id': ObjectId('6a0c94afb1dae384ec190a03'), 'case_id': 'EZYV24467', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 3975, 'yr_of_estab': 1977, 'region_of_employment': 'West', 'prevailing_wage': 7902.94, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49947: {'_id': ObjectId('6a0c94afb1dae384ec190a04'), 'case_id': 'EZYV24468', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 94, 'yr_of_estab': 1841, 'region_of_employment': 'South', 'prevailing_wage': 118981.15, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Denied'}
49948: {'_id': ObjectId('6a0c94afb1dae384ec190a05'), 'case_id': 'EZYV24469', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 452, 'yr_of_estab': 2012, 'region_of_employment': 'Northeast', 'prevailing_wage': 37046.81, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49949: {'_id': ObjectId('6a0c94afb1dae384ec190a06'), 'case_id': 'EZYV24470', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1905, 'yr_of_estab': 1984, 'region_of_employment': 'Midwest', 'prevailing_wage': 87528.16, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49950: {'_id': ObjectId('6a0c94afb1dae384ec190a07'), 'case_id': 'EZYV24471', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 3967, 'yr_of_estab': 2012, 'region_of_employment': 'West', 'prevailing_wage': 32685.63, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49951: {'_id': ObjectId('6a0c94afb1dae384ec190a08'), 'case_id': 'EZYV24472', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1139, 'yr_of_estab': 2000, 'region_of_employment': 'West', 'prevailing_wage': 122358.8, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49952: {'_id': ObjectId('6a0c94afb1dae384ec190a09'), 'case_id': 'EZYV24473', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2556, 'yr_of_estab': 2005, 'region_of_employment': 'Midwest', 'prevailing_wage': 150781.04, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49953: {'_id': ObjectId('6a0c94afb1dae384ec190a0a'), 'case_id': 'EZYV24474', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1892, 'yr_of_estab': 1988, 'region_of_employment': 'Northeast', 'prevailing_wage': 242247.08, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
49954: {'_id': ObjectId('6a0c94afb1dae384ec190a0b'), 'case_id': 'EZYV24475', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 28900, 'yr_of_estab': 1987, 'region_of_employment': 'South', 'prevailing_wage': 89990.75, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49955: {'_id': ObjectId('6a0c94afb1dae384ec190a0c'), 'case_id': 'EZYV24476', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2253, 'yr_of_estab': 1999, 'region_of_employment': 'South', 'prevailing_wage': 161.556, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Denied'}
49956: {'_id': ObjectId('6a0c94afb1dae384ec190a0d'), 'case_id': 'EZYV24477', 'continent': 'North America', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1312, 'yr_of_estab': 2006, 'region_of_employment': 'Northeast', 'prevailing_wage': 114921.14, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49957: {'_id': ObjectId('6a0c94afb1dae384ec190a0e'), 'case_id': 'EZYV24478', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 33013, 'yr_of_estab': 2003, 'region_of_employment': 'South', 'prevailing_wage': 107511.67, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49958: {'_id': ObjectId('6a0c94afb1dae384ec190a0f'), 'case_id': 'EZYV24479', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 225, 'yr_of_estab': 1983, 'region_of_employment': 'Northeast', 'prevailing_wage': 11228.83, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49959: {'_id': ObjectId('6a0c94afb1dae384ec190a10'), 'case_id': 'EZYV24480', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1489, 'yr_of_estab': 1943, 'region_of_employment': 'West', 'prevailing_wage': 41943.52, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
49960: {'_id': ObjectId('6a0c94afb1dae384ec190a11'), 'case_id': 'EZYV24481', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 819, 'yr_of_estab': 1871, 'region_of_employment': 'West', 'prevailing_wage': 28226.79, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49961: {'_id': ObjectId('6a0c94afb1dae384ec190a12'), 'case_id': 'EZYV24482', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2990, 'yr_of_estab': 2000, 'region_of_employment': 'Midwest', 'prevailing_wage': 235875.97, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49962: {'_id': ObjectId('6a0c94afb1dae384ec190a13'), 'case_id': 'EZYV24483', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 28098, 'yr_of_estab': 2008, 'region_of_employment': 'South', 'prevailing_wage': 176127.02, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49963: {'_id': ObjectId('6a0c94afb1dae384ec190a14'), 'case_id': 'EZYV24484', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 321, 'yr_of_estab': 2005, 'region_of_employment': 'Midwest', 'prevailing_wage': 100105.94, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49964: {'_id': ObjectId('6a0c94afb1dae384ec190a15'), 'case_id': 'EZYV24485', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 70128, 'yr_of_estab': 2005, 'region_of_employment': 'Northeast', 'prevailing_wage': 60057.29, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49965: {'_id': ObjectId('6a0c94afb1dae384ec190a16'), 'case_id': 'EZYV24486', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 707, 'yr_of_estab': 2006, 'region_of_employment': 'Northeast', 'prevailing_wage': 106817.92, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49966: {'_id': ObjectId('6a0c94afb1dae384ec190a17'), 'case_id': 'EZYV24487', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2322, 'yr_of_estab': 1888, 'region_of_employment': 'Northeast', 'prevailing_wage': 44108.63, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
49967: {'_id': ObjectId('6a0c94afb1dae384ec190a18'), 'case_id': 'EZYV24488', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3783, 'yr_of_estab': 2004, 'region_of_employment': 'Northeast', 'prevailing_wage': 76081.23, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49968: {'_id': ObjectId('6a0c94afb1dae384ec190a19'), 'case_id': 'EZYV24489', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 994, 'yr_of_estab': 2005, 'region_of_employment': 'West', 'prevailing_wage': 79652.4, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49969: {'_id': ObjectId('6a0c94afb1dae384ec190a1a'), 'case_id': 'EZYV24490', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 714, 'yr_of_estab': 2005, 'region_of_employment': 'West', 'prevailing_wage': 106.43, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Denied'}
49970: {'_id': ObjectId('6a0c94afb1dae384ec190a1b'), 'case_id': 'EZYV24491', 'continent': 'South America', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 1477, 'yr_of_estab': 2004, 'region_of_employment': 'West', 'prevailing_wage': 92861.12, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49971: {'_id': ObjectId('6a0c94afb1dae384ec190a1c'), 'case_id': 'EZYV24492', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3904, 'yr_of_estab': 1998, 'region_of_employment': 'West', 'prevailing_wage': 87364.63, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
49972: {'_id': ObjectId('6a0c94afb1dae384ec190a1d'), 'case_id': 'EZYV24493', 'continent': 'South America', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2716, 'yr_of_estab': 1911, 'region_of_employment': 'West', 'prevailing_wage': 56111.63, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
49973: {'_id': ObjectId('6a0c94afb1dae384ec190a1e'), 'case_id': 'EZYV24494', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 690, 'yr_of_estab': 1904, 'region_of_employment': 'Northeast', 'prevailing_wage': 131704.23, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
49974: {'_id': ObjectId('6a0c94afb1dae384ec190a1f'), 'case_id': 'EZYV24495', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 976, 'yr_of_estab': 1897, 'region_of_employment': 'Midwest', 'prevailing_wage': 29918.19, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49975: {'_id': ObjectId('6a0c94afb1dae384ec190a20'), 'case_id': 'EZYV24496', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3473, 'yr_of_estab': 1921, 'region_of_employment': 'Midwest', 'prevailing_wage': 76756.53, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49976: {'_id': ObjectId('6a0c94afb1dae384ec190a21'), 'case_id': 'EZYV24497', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 88, 'yr_of_estab': 2011, 'region_of_employment': 'Midwest', 'prevailing_wage': 229568.14, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49977: {'_id': ObjectId('6a0c94afb1dae384ec190a22'), 'case_id': 'EZYV24498', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1176, 'yr_of_estab': 1970, 'region_of_employment': 'West', 'prevailing_wage': 76037.92, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49978: {'_id': ObjectId('6a0c94afb1dae384ec190a23'), 'case_id': 'EZYV24499', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 5170, 'yr_of_estab': 1979, 'region_of_employment': 'Northeast', 'prevailing_wage': 89875.48, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49979: {'_id': ObjectId('6a0c94afb1dae384ec190a24'), 'case_id': 'EZYV24500', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 394, 'yr_of_estab': 1995, 'region_of_employment': 'West', 'prevailing_wage': 56232.81, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49980: {'_id': ObjectId('6a0c94afb1dae384ec190a25'), 'case_id': 'EZYV24501', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1635, 'yr_of_estab': 1995, 'region_of_employment': 'Northeast', 'prevailing_wage': 108079.45, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49981: {'_id': ObjectId('6a0c94afb1dae384ec190a26'), 'case_id': 'EZYV24502', 'continent': 'North America', 'education_of_employee': 'Doctorate', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2517, 'yr_of_estab': 1961, 'region_of_employment': 'South', 'prevailing_wage': 80705.19, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
49982: {'_id': ObjectId('6a0c94afb1dae384ec190a27'), 'case_id': 'EZYV24503', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1612, 'yr_of_estab': 1951, 'region_of_employment': 'Northeast', 'prevailing_wage': 530.9247, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Denied'}
49983: {'_id': ObjectId('6a0c94afb1dae384ec190a28'), 'case_id': 'EZYV24504', 'continent': 'Europe', 'education_of_employee': 'Doctorate', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 580, 'yr_of_estab': 1965, 'region_of_employment': 'West', 'prevailing_wage': 31403.73, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}

In [13]:
df = pd.DataFrame(list(collection.find()))
df.head()

,_id,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,6a0c92e7a6fc024582dfd226,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,6a0c92e7a6fc024582dfd227,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,6a0c92e7a6fc024582dfd228,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,6a0c92e7a6fc024582dfd229,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,6a0c92e7a6fc024582dfd22a,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [16]:
df = df.drop(columns = ["_id"], axis =1)

In [19]:
df.sample(10)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
21487,EZYV21488,Asia,Master's,N,N,2071,2003,West,986.8139,Hour,Y,Certified
20188,EZYV20189,Asia,Master's,N,N,2808,1989,Midwest,122828.9400,Year,Y,Certified
17070,EZYV17071,Asia,Doctorate,Y,N,3813,1962,Midwest,45001.9600,Year,Y,Certified
6405,EZYV6406,Asia,Master's,N,N,1229,1994,West,112505.4600,Year,Y,Certified
37923,EZYV12444,North America,Master's,Y,N,133,2003,Northeast,141099.6600,Year,N,Certified
21319,EZYV21320,Asia,Master's,Y,N,3055,2000,West,119928.3100,Year,Y,Denied
50386,EZYV24907,Asia,Master's,N,N,2675,2006,South,135066.2900,Year,Y,Certified
35387,EZYV9908,Asia,Master's,N,N,783,2006,Midwest,90245.3800,Year,Y,Certified
40522,EZYV15043,Asia,Bachelor's,Y,N,3143,2000,Midwest,147481.0100,Year,Y,Certified
28617,EZYV3138,Asia,Doctorate,N,Y,61396,1987,Midwest,242406.3200,Year,Y,Denied